### ISSUE TITLE
New Chapter: Sylhet , Bangladesh

### ISSUE THREAD

**Issue by hashemirafsan** [nodeschool/organizers#423] opened 2017-03-08 19:02 UTC
Hi, I would like to start a nodeschool chapter for sylhet. I am Rafsanhashemi on twitter and work at Authlab . I have been using Node.js for 6 months and would like to help others learn as well

**Comment by riyadhalnur** [comment] 2017-03-09 01:00
Duplicate of #398.

**Closed by riyadhalnur** 2017-03-09 01:00 UTC
