### ISSUE TITLE
Vienna chapter

### ISSUE THREAD

**Issue by simoneb** [nodeschool/organizers#186] opened 2015-03-31 20:18 UTC
Hi, I would like to start a nodeschool chapter for Vienna, Austria. I am @simonebu on twitter and I am a freelance. I will be co-organizing this chapter with (people to be defined yet). I have been using Node.js for a few years and would like to help others learn as well.

**Comment by martinheidegger** [comment] 2015-04-03 08:50
@simoneb It seems like this is a duplicate of https://github.com/nodeschool/organizers/issues/188 can you talk with @thomaspeklak about organising it together?

**Closed by martinheidegger** 2015-04-03 08:50 UTC
Labels: chapter request

**Comment by simoneb** [comment] 2015-04-03 08:57
considering that this is #186 eventually it's #188 a duplicate of this, but nevermind

**Comment by martinheidegger** [comment] 2015-04-03 09:09
@simoneb Sorry for the wrong processing order. I am sure @finnp didn't think any of it. We try to avoid having multiple chapters at the same location so It was very nice of you to ask to join them! Thank you!

**Comment by simoneb** [comment] 2015-04-03 09:10
Sure, np at all, was just pointing out :)
